// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_uyZnKihZLUfC8v9YBMNu-bhFnSL6cUI',
    appId: '1:781625654833:web:27844a07fa000a30981f10',
    messagingSenderId: '781625654833',
    projectId: 'cropsentry-9c043',
    authDomain: 'cropsentry-9c043.firebaseapp.com',
    storageBucket: 'cropsentry-9c043.firebasestorage.app',
    measurementId: 'G-T84WVSDH1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhs9DeMGNnYLsHZpEEIIyWdO9y59s71f8',
    appId: '1:781625654833:android:a74a1b4ba610d6a0981f10',
    messagingSenderId: '781625654833',
    projectId: 'cropsentry-9c043',
    storageBucket: 'cropsentry-9c043.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUAQu51gl9lgTU2aRtiNQfrjwH97GC3fw',
    appId: '1:781625654833:ios:d7a6f9d96461a82b981f10',
    messagingSenderId: '781625654833',
    projectId: 'cropsentry-9c043',
    storageBucket: 'cropsentry-9c043.firebasestorage.app',
    iosBundleId: 'com.example.cropSentry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUAQu51gl9lgTU2aRtiNQfrjwH97GC3fw',
    appId: '1:781625654833:ios:d7a6f9d96461a82b981f10',
    messagingSenderId: '781625654833',
    projectId: 'cropsentry-9c043',
    storageBucket: 'cropsentry-9c043.firebasestorage.app',
    iosBundleId: 'com.example.cropSentry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_uyZnKihZLUfC8v9YBMNu-bhFnSL6cUI',
    appId: '1:781625654833:web:50d7d8308328a3ca981f10',
    messagingSenderId: '781625654833',
    projectId: 'cropsentry-9c043',
    authDomain: 'cropsentry-9c043.firebaseapp.com',
    storageBucket: 'cropsentry-9c043.firebasestorage.app',
    measurementId: 'G-SZM5B35GZ1',
  );
}
